server:
  host: "127.0.0.1"
  port: 12134
db:
  mysql:
    host: "101.43.247.25"
    port: 16033
    username: "liuzhineng"
    password: "woshiliuwen@1"
    database: "lzn"
jwt:
  signingKey: "www.i2dou.com"
  expiresTime: "1h"
  bufferTime: "1d"
  issuer: "lvg"